server:
  port: 9002
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true #feign使用okhttp去调用微服务
    
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）

logging:
  level:
    root: info
    com.yy.auth: debug

# LogStash访问,elk日志收集
logstash:
  host: 192.168.205.232